name:                rea
version:             0.1.0.0
github:              "githubuser/rea"
license:             BSD3
author:              "Nikolay Burkov"
maintainer:          "nbrk@linklevel.net"
copyright:           "2019 Nikolay Burkov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Resource-Entity-Action design
                     pattern for declarative
                     descriptions of RTS games
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rea#readme>

dependencies:
- base >= 4.7 && < 5
- microlens
- containers
- mtl

library:
  source-dirs: src

executables:
  rea-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rea
    - linear
    - microlens
    - microlens-th
    - sdl2
    - criterion

tests:
  rea-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rea
